services:
  - type: web
    name: kick-noorgamer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
