services:
  - type: web
    name: kick-noorgamer
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: CHROME_BINARY
        value: /usr/bin/chromium-browser
